# Generated by Django 4.2.4 on 2023-08-30 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_minithread_created_at_minithread_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='minithread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minithread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
